// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20240225172253_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Name = "Frederik",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Name = "Nicolai",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Name = "Wolfram",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Name = "Yevgeny",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Name = "Milosz",
                            Species = "Dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
